TimefoldAI/timefold-solver

- migration/src/main/resources/META-INF/rewrite/FromOptaPlannerToTimefoldSolver.yml
> feat: migrate Logback to Timefold too

- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/BreakImpl.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/ComparableValue.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/ConsecutiveIntervalInfoImpl.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/ConsecutiveSetTree.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/Interval.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/IntervalClusterImpl.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/IntervalTree.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/IntervalTreeIterator.java
- examples/src/main/java/ai/timefold/solver/examples/common/experimental/impl/SequenceImpl.java
Improves nurse rostering performance by ~15 %.
> perf: speed up CS consecutive collector

- tools/webui/src/main/resources/META-INF/resources/webjars/timefold/css/timefold-webui.css
https://github.com/TimefoldAI/timefold-quickstarts/issues/45
> fix: dark navbars miss contrast

- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/variable/listener/support/VariableListenerSupport.java
- core/core-impl/src/test/java/ai/timefold/solver/core/api/solver/SolutionManagerTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/list/shadow_history/TestdataListWithShadowHistoryIncrementalScoreCalculator.java
- core/core-impl/src/test/resources/ai/timefold/solver/core/api/solver/testdataListWithShadowHistorySolverConfig.xml
The code path to handle list variables was entirely missing.
> fix: make SolutionManager.update() work on list variable as well

- README.adoc
Updated the README with references to OptaPlanner
> Update README.adoc with OptaPlanner reference

- build/bom/pom.xml
- build/build-parent/pom.xml
- quarkus-integration/quarkus-benchmark/deployment/pom.xml
- quarkus-integration/quarkus-benchmark/integration-test/pom.xml
- quarkus-integration/quarkus-benchmark/pom.xml
- quarkus-integration/quarkus-benchmark/runtime/pom.xml
- quarkus-integration/quarkus-jackson/deployment/pom.xml
- quarkus-integration/quarkus-jackson/integration-test/pom.xml
- quarkus-integration/quarkus-jackson/pom.xml
- quarkus-integration/quarkus-jackson/runtime/pom.xml
- quarkus-integration/quarkus-jsonb/deployment/pom.xml
- quarkus-integration/quarkus-jsonb/integration-test/pom.xml
- quarkus-integration/quarkus-jsonb/pom.xml
- quarkus-integration/quarkus-jsonb/runtime/pom.xml
- quarkus-integration/quarkus/deployment/pom.xml
- quarkus-integration/quarkus/devui-integration-test/pom.xml
- quarkus-integration/quarkus/integration-test/pom.xml
- quarkus-integration/quarkus/pom.xml
- quarkus-integration/quarkus/reflection-integration-test/pom.xml
- quarkus-integration/quarkus/runtime/pom.xml
Otherwise the URL on Maven Central for each of the submodules will lead to timefold.ai/submodule/subsubmodule ...
> chore: set URL in all POMs

- README.adoc
Added a link to Enterprise edition as well as rephrasing the licensing and usage section
> Docs: Update README.adoc

- core/constraint-streams/src/test/java/ai/timefold/solver/constraint/streams/common/AbstractConstraintStreamTest.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/analysis/ConstraintAnalysis.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/analysis/MatchAnalysis.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/constraint/ConstraintMatch.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/ConstraintBuilder.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/ConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/bi/BiConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/quad/QuadConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/tri/TriConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/uni/UniConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/DefaultScoreExplanation.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/InnerScoreDirector.java
- core/core-impl/src/test/java/ai/timefold/solver/core/api/score/analysis/ScoreAnalysisTest.java
- docs/src/modules/ROOT/pages/constraints-and-score/understanding-the-score.adoc
- examples/src/main/java/ai/timefold/solver/examples/common/swingui/SolutionPanel.java
- examples/src/main/java/ai/timefold/solver/examples/conferencescheduling/persistence/ConferenceSchedulingXlsxFileIO.java
- examples/src/main/java/ai/timefold/solver/examples/meetingscheduling/persistence/MeetingSchedulingXlsxFileIO.java
- persistence/jackson/src/main/java/ai/timefold/solver/jackson/api/TimefoldJacksonModule.java
- persistence/jackson/src/main/java/ai/timefold/solver/jackson/api/score/analysis/AbstractScoreAnalysisJacksonDeserializer.java
- persistence/jackson/src/main/java/ai/timefold/solver/jackson/api/score/constraint/ConstraintRefJacksonDeserializer.java
- persistence/jackson/src/main/java/ai/timefold/solver/jackson/api/score/constraint/ConstraintRefJacksonSerializer.java
- persistence/jackson/src/test/java/ai/timefold/solver/jackson/api/TimefoldJacksonModuleTest.java
Score corruption analysis now reuses score analysis.
Also ties some loose ends which did not fit into c6239331dab00e08b1ba6edf90d4fa642a723ce7.
> chore: clean up after the introduction of ScoreAnalysis

- docs/src/modules/ROOT/images/use-cases-and-examples/vehicle-routing/vehicleRoutingClassDiagram.svg
- examples/data/taskassigning/unsolved/100tasks-5employees.json
- examples/data/taskassigning/unsolved/24tasks-8employees.json
- examples/data/taskassigning/unsolved/500tasks-20employees.json
- examples/data/taskassigning/unsolved/50tasks-5employees.json
- examples/data/vehiclerouting/unsolved/cvrptw-100customers-A.json
- examples/data/vehiclerouting/unsolved/cvrptw-100customers-B.json
- examples/data/vehiclerouting/unsolved/cvrptw-25customers.json
- examples/data/vehiclerouting/unsolved/cvrptw-400customers.json
- examples/src/main/java/ai/timefold/solver/examples/taskassigning/domain/Task.java
- examples/src/main/java/ai/timefold/solver/examples/taskassigning/domain/solver/StartTimeUpdatingVariableListener.java
- examples/src/main/java/ai/timefold/solver/examples/taskassigning/swingui/TaskAssigningPanel.java
- examples/src/main/java/ai/timefold/solver/examples/taskassigning/swingui/TaskOverviewPanel.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/domain/timewindowed/TimeWindowedCustomer.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/domain/timewindowed/TimeWindowedDepot.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/domain/timewindowed/solver/ArrivalTimeUpdatingVariableListener.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/optional/score/VehicleRoutingEasyScoreCalculator.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/optional/score/VehicleRoutingIncrementalScoreCalculator.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/persistence/VehicleRoutingImporter.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/score/VehicleRoutingConstraintProvider.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/swingui/VehicleRoutingPanel.java
- examples/src/main/java/ai/timefold/solver/examples/vehiclerouting/swingui/VehicleRoutingSolutionPainter.java
- examples/src/test/java/ai/timefold/solver/examples/vehiclerouting/score/VehicleRoutingConstraintProviderTest.java
> chore: replace ready/due time by min/max start/end time

- docs/src/modules/ROOT/pages/constraints-and-score/understanding-the-score.adoc
> docs: fix method references for score explanation

- docs/src/modules/ROOT/pages/constraints-and-score/score-calculation.adoc
- docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
This pull request updates the documentation for constraints and renames variable names for collection types using the pattern `<name>List`.
Issue TimefoldAI/timefold-quickstarts#19
> fix:Renaming variable names for collection types

- docs/src/modules/ROOT/pages/_attributes.adoc
Fixes #520
Note: Opted for tarball url, suppose it doesn't matter if tar or zip 🤷
> fix: correct quickstarts-archive-url

- build/build-parent/pom.xml
One plugin to rule them all.
Follow-up:
https://github.com/TimefoldAI/timefold-solver-enterprise/pull/64
> build: replace formatter and impsort with spotless

- .github/workflows/sonarcloud.yml
This PR re-enables the SonarCloud workflow.
> ci: Re-enabling the SonarCloud workflow

- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/ScoreDirectorFactoryFactory.java
This PR is for issue #690. It's a very simple 1-line change.
> fix: pass provided class loader to service loader

- core/core-impl/src/main/java/ai/timefold/solver/core/config/solver/SolverConfig.java
> feat: add withClassLoader method to SolverConfig

- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/bigdecimal/BigDecimalValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/biginteger/BigIntegerValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/collection/ListValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/composite/CompositeCountableValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/composite/EmptyValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/primboolean/BooleanValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/primint/IntValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/primlong/LongValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/temporal/TemporalValueRange.java
- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/kopt/EntityOrderInfo.java
Tweaking assorted small things to make Sonar happy.
> chore: bring Sonar reliability rating back to green

- core/src/main/java/ai/timefold/solver/core/impl/domain/variable/descriptor/ListVariableDescriptor.java
- core/src/main/java/ai/timefold/solver/core/impl/heuristic/move/Move.java
- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/ListAssignMove.java
- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/ListUnassignMove.java
- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/SubListUnassignMove.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/AllowsUnassignedValuesListVariableSolverTest.java
> fix: Simplified moves need to list their entities and values

- build/build-parent/pom.xml
> chore: downgrade Quarkus to 3.8.3

- docs/src/modules/ROOT/pages/enterprise-edition/enterprise-edition.adoc
https://help.ahrefs.com/en/articles/2614035-https-page-has-internal-links-to-http-error-in-site-audit
> fix: ahrefs was complaining about this link

- docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/quarkus-vehicle-routing/quarkus-vehicle-routing-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
This PR renames the maven artifacts due to changes from TimefoldAi/timefold-quickstarts#416
> chore: Renaming Maven Artifacts

- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/common/AbstractJoinNode.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/common/index/ComparisonIndexer.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/collector/MinMaxUndoableActionable.java
- Iterating manually in join allows to create much less instances of `Iterator`, reducing GC pressure significantly.
- min/max constraint collector was needlessly using a `Map`, which only ever had one key.
In cases particularly exposed to these issues, the performance improvements seen were ~ 10 %.
> perf: minor improvements to Constraint Streams

- core/src/main/java/ai/timefold/solver/core/impl/score/stream/collector/MinMaxUndoableActionable.java
I will get back to it one day. But for now, I'm reverting the change.
> revert: min/max collector perf improvement was causing score corruptions

- benchmark/src/main/java/ai/timefold/solver/benchmark/impl/report/LineChart.java
Otherwise we see test failures on M3 Macs.
> test: use less double in LineChart

- python/python-core/src/main/python/score/_group_by.py
Required for https://github.com/TimefoldAI/timefold-quickstarts/pull/517
> fix: proper casts in Python load_balance collector

- quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/DotNames.java
- quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java
- quarkus-integration/quarkus/integration-test/src/main/java/ai/timefold/solver/quarkus/it/domain/TestdataStringLengthShadowSolution.java
This pull request adds the `ConstraintWeightOverrides` access member for native compilation.
> fix: register the `ConstraintWeightOverrides` access member for native compilation

- .github/workflows/downstream_benchmarks.yml
- .github/workflows/downstream_enterprise.yml
- .github/workflows/downstream_python_enterprise.yml
- .github/workflows/sonarcloud.yml
The org membership test failed on a github actor name containing brackets, such as 'dependabot[bot]'.
> fix: github actor with brackets

- docs/src/modules/ROOT/pages/optimization-algorithms/move-selector-reference.adoc
Fix selectors + remove pillar (coarse grained move of its own).
> fix: Ruin and recreate doc updates

- docs/src/modules/ROOT/pages/introduction/introduction.adoc
I noticed some more things I wanted to change in the introduction.
> docs: further tweaks to the introduction

- docs/src/modules/ROOT/nav.adoc
- docs/src/modules/ROOT/pages/introduction.adoc
Inspired by comments on: https://github.com/TimefoldAI/timefold-orbit/pull/1868. Re-Aligning again.
> docs: improve similarity with other books.

- docs/src/modules/ROOT/nav.adoc
- docs/src/modules/ROOT/pages/frequently-asked-questions.adoc
Apparently, the FAQ section never made it to the nav. I added it there and also expanded a bit on the use in a native application.
> docs: add FAQ section

- core/src/main/java/ai/timefold/solver/core/config/solver/SolverConfig.java
- core/src/test/java/ai/timefold/solver/core/config/solver/SolverConfigTest.java
Also cleaning up the associated test class.
> feat: Add method to SolverConfig for setting unimproved spent limit termination

- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/common/AbstractJoinNode.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/common/tuple/AbstractTuple.java
We were being too clever and the clever approach doesn't seem justified.
This improves performance in the benchmarks by 3 to 6 percent.
> perf: improve tuple store performance

- quarkus-integration/quarkus/deployment/pom.xml
- quarkus-integration/quarkus/deployment/src/build/revapi-differences.json
- quarkus-integration/quarkus/deployment/src/build/revapi-filter.json
- quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/SolverConfigBuildItem.java
- quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/TimefoldProcessor.java
- quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/api/ConstraintMetaModelBuildItem.java
- quarkus-integration/quarkus/deployment/src/main/java/ai/timefold/solver/quarkus/deployment/api/package-info.java
- quarkus-integration/quarkus/runtime/src/main/java/ai/timefold/solver/quarkus/bean/BeanUtil.java
- quarkus-integration/quarkus/runtime/src/main/java/ai/timefold/solver/quarkus/bean/DefaultTimefoldBeanProvider.java
Fixes https://github.com/TimefoldAI/timefold-solver/issues/1323.
> feat: expose ConstraintMetaModel at build time

- core/src/main/java/ai/timefold/solver/core/api/solver/SolverJob.java
- core/src/main/java/ai/timefold/solver/core/api/solver/SolverManager.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/BestSolutionHolder.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolver.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolverJob.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolverManager.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/BasicPlumbingTermination.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/BestSolutionHolderTest.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/ConsumerSupportTest.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/termination/BasicPlumbingTerminationTest.java
- docs/src/modules/ROOT/pages/responding-to-change/responding-to-change.adoc
> feat: allow SolverManager and SolverJob to submit problem changes in batches

- README.adoc
- benchmark/src/main/resources/ai/timefold/solver/benchmark/impl/report/benchmarkReport.html.ftl
Might need to be adjusted in the enterprise repo too?
> chore: update contact us URL

- docs/src/modules/ROOT/pages/enterprise-edition/enterprise-edition.adoc
- docs/src/modules/ROOT/pages/frequently-asked-questions.adoc
- docs/src/modules/ROOT/pages/introduction.adoc
- docs/src/modules/ROOT/pages/quickstart/overview.adoc
- docs/src/modules/ROOT/pages/quickstart/quarkus-vehicle-routing/quarkus-vehicle-routing-quickstart.adoc
- docs/src/modules/ROOT/pages/using-timefold-solver/modeling-planning-problems.adoc
I expect a review first by @oemebamo and @lee-carlon before making it "un-draft"
> docs: Add references to our pre-built models

- core/src/main/java/ai/timefold/solver/core/impl/domain/solution/descriptor/ProblemScaleTracker.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/solution/descriptor/SolutionDescriptor.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/variable/descriptor/GenuineVariableDescriptor.java
- core/src/test/java/ai/timefold/solver/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java
- core/src/test/java/ai/timefold/solver/core/impl/testdata/domain/list/allows_unassigned/TestdataAllowsUnassignedValuesListSolution.java
This PR updates the statistical calculation method to estimate value counts similarly to how we handle basic variables.
> fix: fix statistics for list variables allowing unassigned values

- docs/src/modules/ROOT/pages/optimization-algorithms/overview.adoc
This PR improves the documentation and adds a note about using diminished termination and bendable score.
> chore: improve diminished doc

- benchmark/src/main/java/ai/timefold/solver/benchmark/config/blueprint/SolverBenchmarkBluePrintType.java
- benchmark/src/main/resources/benchmark.xsd
- core/src/build/revapi-differences.json
- core/src/main/java/ai/timefold/solver/core/config/localsearch/LocalSearchPhaseConfig.java
- core/src/main/java/ai/timefold/solver/core/config/localsearch/LocalSearchType.java
- core/src/main/java/ai/timefold/solver/core/config/localsearch/decider/acceptor/AcceptorType.java
- core/src/main/java/ai/timefold/solver/core/config/solver/PreviewFeature.java
- core/src/main/java/ai/timefold/solver/core/impl/localsearch/DefaultLocalSearchPhaseFactory.java
- core/src/main/java/ai/timefold/solver/core/impl/localsearch/decider/forager/AcceptedLocalSearchForager.java
- core/src/main/java/ai/timefold/solver/core/impl/move/MoveStreamsBasedMoveRepository.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/generic/move/AbstractMove.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/generic/move/ChainedChangeMove.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/generic/move/ChangeMove.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/generic/move/ListAssignMove.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/generic/move/ListChangeMove.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/generic/move/ListUnassignMove.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/generic/provider/ChangeMoveProvider.java
- core/src/main/java/ai/timefold/solver/core/impl/move/streams/maybeapi/stream/MoveProviders.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolverFactory.java
- core/src/main/resources/solver.xsd
- core/src/test/java/ai/timefold/solver/core/impl/move/MoveStreamsBasedLocalSearchTest.java
- core/src/test/java/ai/timefold/solver/core/impl/move/streams/maybeapi/provider/ChangeMoveProviderTest.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/DefaultSolverTest.java
- docs/src/modules/ROOT/pages/upgrading-timefold-solver/backwards-compatibility.adoc
This feature is under heavy development.
Any use is discouraged.
> chore: expose Move Streams as a experimental feature

- docs/src/modules/ROOT/pages/upgrading-timefold-solver/backwards-compatibility.adoc
- docs/src/modules/ROOT/pages/using-timefold-solver/modeling-planning-problems.adoc
Adding draft pull request for Shadow Variable docs. Still need to re-read it.
> docs: shadow variables

- benchmark/src/main/java/ai/timefold/solver/benchmark/impl/loader/FileProblemProvider.java
See bug report #1540 for more details
> fix: Added missing getter and setter for the FileProblemProvider class

- .github/workflows/pull_request.yml
> ci: run on ARM64 as well

- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/kopt/KOptListMoveIterator.java
> fix: avoid more situations where a K-OPT cannot be found

- docs/src/modules/ROOT/pages/using-timefold-solver/modeling-planning-problems.adoc
This removed statement was no longer correct.
> docs: update for ValueRangeProvider on entity support on PlanningListVariable

- docs/src/modules/ROOT/pages/constraints-and-score/understanding-the-score.adoc
This PR replaces the `explain()` method with the `analyse()` one since the former method will be deprecated in the future versions of Timefold (#1805).
> docs: replace solutionManager.explain() with .analyse()
