TimefoldAI/timefold-solver

- build/build-parent/pom.xml
- core/constraint-streams/pom.xml
- core/core-impl/pom.xml
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/common/ReflectionHelper.java
- core/core/pom.xml
- docs/src/modules/ROOT/pages/optimization-algorithms/optimization-algorithms.adoc
- persistence/pom.xml
Timefold Solver does not support Android,
especially as it would force us not to use stuff from recent JDKs.
> build: do not check for Android-unfriendly code

- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/ConstraintCollectors.java
- core/core-impl/src/test/java/ai/timefold/solver/core/api/score/stream/ConstraintCollectorsTest.java
The pre-existing way of doing min/max constraint collectors relied on a user-supplied comparator.
The values would then be put straight into a `TreeMap`, sorted according to this comparator.
However, if the comparator relied on a planning variable, there would be issues.
During insertion, the value would be put into a map.
But then the value's comparison would change due to the planning variable changing.
As a result, on value removal from the map, the value would fail to be removed, leading to exceptions.
The new code no longer relies on user-supplied comparator. 
Instead, it asks the user to supply a function to return the comparable object and creates the comparator internally.
This allows the collector to store the value that was inserted, and on removal, remove that same value; not …
> fix: allow min/max constraint collectors on planning variables

- quarkus-integration/quarkus/runtime/pom.xml
STOPGAP for https://github.com/TimefoldAI/timefold-solver/issues/133
GOOD FIX that is still open: https://github.com/TimefoldAI/timefold-solver/pull/134
> fix(quarkus): Workaround quarkus-run.jar fails fast due to gizmo missing

- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/decider/ConstructionHeuristicDecider.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/placer/PooledEntityPlacerFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/placer/QueuedEntityPlacerFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/placer/QueuedValuePlacerFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/move/CompositeMove.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/entity/decorator/PinEntityFilter.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/AbstractMoveSelectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/DoableMoveSelectionFilter.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/MoveSelectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/composite/AbstractCompositeMoveSelectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/composite/CartesianProductMoveSelector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/composite/UnionMoveSelectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/decorator/FilteringMoveSelector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/localsearch/DefaultLocalSearchPhaseFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/localsearch/decider/LocalSearchDecider.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/MoveSelectorFactoryTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/ChangeMoveSelectorFactoryTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/SwapMoveSelectorFactoryTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/ListChangeMoveSelectorFactoryTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/ListSwapMoveSelectorFactoryTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/SubListChangeMoveSelectorFactoryTest.java
Move selector has supported bail-out for a long time.
However, it did not apply to non-doable moves, so when all the moves were non-doable, the bail-out would never happen.
This change makes bail-out happen for non-doable moves as well, by filtering out non-doable moves directly in the move selector. This requires to force an arbitrary limit on the number of moves that will be evaluated, as not every move selector provides its size.
> fix: bail out of a never-ending loop when no move is doable

- core/core-impl/src/main/java/ai/timefold/solver/core/api/domain/valuerange/ValueRangeFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/solution/descriptor/SolutionDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/AbstractUncountableValueRange.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/buildin/primdouble/DoubleValueRange.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/descriptor/AbstractFromPropertyValueRangeDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/descriptor/CompositeValueRangeDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/descriptor/EntityIndependentValueRangeDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/descriptor/FromEntityPropertyValueRangeDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/descriptor/FromSolutionPropertyValueRangeDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/valuerange/descriptor/ValueRangeDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/variable/descriptor/GenuineVariableDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/value/FromEntityPropertyValueSelector.java
To read an entire value range to get its size,
the value range needs to be first converted to a collection. 
This is costly and we therefore implement a shortcut, 
allowing us to read the size without creating a collection.
> perf: read value range size instead of the value range

- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/BavetConstraintStreamScoreDirector.java
- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/BavetConstraintStreamScoreDirectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/solver/SolutionUpdatePolicy.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/variable/inverserelation/CollectionInverseVariableListener.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/variable/inverserelation/SingletonInverseVariableListener.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/variable/inverserelation/SingletonListInverseVariableListener.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/InnerScoreDirector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/InnerScoreDirectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/easy/EasyScoreDirector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/easy/EasyScoreDirectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/incremental/IncrementalScoreDirector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/score/director/incremental/IncrementalScoreDirectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolutionManager.java
- core/core-impl/src/test/java/ai/timefold/solver/core/api/solver/SolutionManagerTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/score/director/easy/EasyScoreDirectorFactoryTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/score/director/easy/EasyScoreDirectorTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/score/director/incremental/IncrementalScoreDirectorTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/chained/shadow/TestdataShadowingChainedIncrementalScoreCalculator.java
- core/core-impl/src/test/resources/ai/timefold/solver/core/api/solver/testdataShadowingChainedSolverConfig.xml
There is a fail fast to detect that an inverse var points to the incorrect inverse.
But update() is used to fix those cases, so the fail-fast must not trigger there.
> fix: avoid fail-fast to fix SolutionManager.update() on chained var

- build/build-parent/pom.xml
Java 21 is not on GHA yet, but I tested this locally and it works.
Replaces https://github.com/TimefoldAI/timefold-solver/pull/299.
> deps: remove ASM overrides

- jreleaser.yml
Changed my mind; release notes should include version bumps.
> ci: don't remove dependabot from release notes

- core/core-impl/src/main/java/ai/timefold/solver/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/AbstractMoveSelectorFactory.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/exhaustivesearch/BruteForceTest.java
Fixes a regression introduced by 0bc4ec1.
Exhaustive search works in a similar way to construction heuristics, and as such moves to `null` must be made available even if they're changing `null` to `null`, making them technically non-doable.
> fix: exhaustive search must not skip non-doable moves

- core/core-impl/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/entity/descriptor/EntityDescriptor.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/solution/cloner/DeepCloningFieldCloner.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/solution/cloner/DeepCloningUtils.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/solution/cloner/FieldAccessingSolutionCloner.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/solution/descriptor/SolutionDescriptor.java
- core/core-impl/src/test/java/ai/timefold/solver/core/config/solver/SolverConfigTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/domain/solution/cloner/AbstractSolutionClonerTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/clone/deepcloning/TestdataVariousTypes.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/record/TestdataRecordEntity.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/record/TestdataRecordSolution.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/record/TestdataRecordValue.java
- docs/src/modules/ROOT/pages/configuration/configuration.adoc
Does several things:
1. Records can serve as planning variables; planning ID annotation on record components no longer throws.
2. Records can no longer be solutions or entities, as these need to be mutable.
3. Records are no longer deep-cloned, receiving the same treatment as enums.
4. Throws a better exception when cloning fails due to an exception in constructor.
The second and third change are technically backwards incompatible behavior but we introduce it anyway, as the old behavior was erroneous.
> feat: improve support for Java records

- .github/workflows/pull_request.yml
JDK 21 build status:
https://github.com/adoptium/temurin/issues/8
> ci: replace JDK 20 with 21

- docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
Split up `Maven` and `Gradle` examples in tabs as an example on how to use `asccidoctor-tabs` that is now added as an option to the docs on timefold.ai website.
> docs: Example on how to use asciidoctor-tabs in docs

- docs/src/modules/ROOT/pages/constraints-and-score/performance.adoc
Updates the OptaPlanner blog and brings it into the documentation.
Closes #109.
> docs: add section on CS performance

- docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/school-timetabling/school-timetabling-constraints.adoc
- docs/src/modules/ROOT/pages/quickstart/school-timetabling/school-timetabling-model.adoc
- docs/src/modules/ROOT/pages/quickstart/school-timetabling/school-timetabling-solution.adoc
- docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
This pull request contains updates related to the School Timetabling quickstart. Here are some important points:
- The field `id` was not included in the problem facts to keep them simple.
- The OpenAPI dependencies were not included to keep things simple.
- The justification models were not included to keep things simple.
- The initial Maven and Gradle files were modified to remove test dependencies and then add them in the test Section.
Issue #98
> fix: Updating the School Timetabling quickstarts documentation

- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/analysis/MatchAnalysis.java
when performing score corruption analysis with more than one excess/missing MatchAnalysis element.
> Issue #526: Fix ClassCastException of MatchAnalysis to Comparable

- core/core-impl/src/main/java/ai/timefold/solver/core/impl/domain/solution/cloner/DeepCloningUtils.java
The docs already say this is impossible, so we're only bringing the impl up to date with the spec.
> fix: fail fast when @DeepPlanningClone on a record

- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/common/AbstractIfExistsNode.java
- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/common/AbstractIndexedIfExistsNode.java
- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/common/AbstractJoinNode.java
- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/common/AbstractUnindexedIfExistsNode.java
- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/common/AbstractUnindexedJoinNode.java
- core/constraint-streams/src/main/java/ai/timefold/solver/constraint/streams/bavet/common/index/EqualsIndexer.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/util/ElementAwareList.java
Various CS nodes could allocate gigabytes of `ElementAwareListIterator` per minute.
We refactor the code so that iterator instances are shared, removing this needless source of GC pressure.
Improves performance of some benchmarks by up to 6 %, while reducing their memory consumption by ~20 %.
> perf: reduce allocations in CS

- spring-integration/spring-boot-autoconfigure/src/main/java/ai/timefold/solver/spring/boot/autoconfigure/TimefoldBenchmarkAutoConfiguration.java
- spring-integration/spring-boot-autoconfigure/src/test/java/ai/timefold/solver/spring/boot/autoconfigure/TimefoldMultipleSolverAutoConfigurationTest.java
This pull request fixes an initialization error that occurs when multiple resources are being used. The error occurs because the Benchmark resources are created in an eager way.
> fix: Avoid eager initialization of the Benchmark resources

- quarkus-integration/quarkus-benchmark/deployment/src/test/java/ai/timefold/solver/benchmark/quarkus/TimefoldBenchmarkProcessorBenchmarkEmptyTerminationConfigTest.java
- quarkus-integration/quarkus-benchmark/deployment/src/test/java/ai/timefold/solver/benchmark/quarkus/TimefoldBenchmarkProcessorMissingSpentLimitWithXmlTest.java
- quarkus-integration/quarkus-benchmark/deployment/src/test/resources/emptySolverBenchmarkConfig.xml
- quarkus-integration/quarkus-benchmark/runtime/src/main/java/ai/timefold/solver/benchmark/quarkus/TimefoldBenchmarkRecorder.java
This pull request fixes a bug in the Quarkus Benchmark extension that was causing the termination properties to be ignored.
> fix: Ensuring the spent termination property is read in the Quarkus environment

- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/placer/EntityPlacer.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/placer/PooledEntityPlacer.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/placer/QueuedEntityPlacer.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/placer/QueuedValuePlacer.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/common/decorator/CompositeSelectionFilter.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/common/decorator/SelectionFilter.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/entity/EntitySelectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/entity/decorator/FilteringEntitySelector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/AbstractMoveSelectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/decorator/FilteringMoveSelector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/ListChangeMoveSelector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/value/ValueSelectorFactory.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/value/decorator/EntityIndependentFilteringValueSelector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/value/decorator/FilteringValueSelector.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/solver/FitProcessor.java
- core/core-impl/src/test/java/ai/timefold/solver/core/api/solver/SolutionManagerTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/entity/decorator/FilteringEntitySelectorTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/decorator/FilteringMoveSelectorTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/PillarDemandTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/value/decorator/EntityIndependentFilteringValueSelectorTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/value/decorator/FilteringValueSelectorTest.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/list/pinned/index/TestdataPinnedWithIndexListCMAIncrementalScoreCalculator.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/list/pinned/index/TestdataPinnedWithIndexListValue.java
- core/core-impl/src/test/java/ai/timefold/solver/core/impl/testdata/domain/nullable/TestdataNullableIncrementalScoreCalculator.java
With nullable vars, the solution may contain many unassigned entities/values.
But the user only wants recommendations for the one that they specified.
Therefore we need to ignore every other one.
I also marginally improve composite filters, deduplicating and decomposing where possible.
Closes #581.
> fix: Recommended Fit API needs to ignore any unassigned entities/values

- .github/workflows/sonarcloud.yml
This pull request modifies the SonarCloud workflow to function with forked repositories as well. The `pull_request_target` event works similarly to `pull_request`, but runs on the base branch and allows using secrets. Therefore, the PR ref version needs to be specified in the workflow script.
> chore: Enabling SonarCloud for forks

- core/constraint-streams/src/test/java/ai/timefold/solver/constraint/streams/common/ConstraintStreamFunctionalTest.java
- core/constraint-streams/src/test/java/ai/timefold/solver/constraint/streams/common/bi/AbstractBiConstraintStreamTest.java
- core/constraint-streams/src/test/java/ai/timefold/solver/constraint/streams/common/quad/AbstractQuadConstraintStreamTest.java
- core/constraint-streams/src/test/java/ai/timefold/solver/constraint/streams/common/tri/AbstractTriConstraintStreamTest.java
- core/constraint-streams/src/test/java/ai/timefold/solver/constraint/streams/common/uni/AbstractUniConstraintStreamTest.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/bi/BiConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/quad/QuadConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/tri/TriConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/api/score/stream/uni/UniConstraintStream.java
- core/core-impl/src/main/java/ai/timefold/solver/core/impl/util/ConstantLambdaUtils.java
This pull request introduces two new penalty methods for `long` and `BigDecimal` values without a match weighter.
> feat: Adding penalty methods for `long` and `BigDecimal` values without match weighter

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_native.yml
Will only become green after Java 22 is universally available.
> ci: introduce Java 22 and split Native into its own job

- core/src/main/java/ai/timefold/solver/core/impl/heuristic/move/Move.java
- core/src/main/java/ai/timefold/solver/core/impl/heuristic/move/NoChangeMove.java
- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/ListUnassignMove.java
- core/src/test/java/ai/timefold/solver/core/impl/heuristic/move/NoChangeMoveTest.java
- core/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/list/ListUnassignMoveTest.java
Otherwise construction heuristics is going
to fail with multi-threaded solving,
when list variable with unassigned values is used.
> fix: add rebase support to NoChangeMove and ListUnassignMove

- core/src/main/java/ai/timefold/solver/core/impl/constructionheuristic/scope/ConstructionHeuristicPhaseScope.java
- core/src/main/java/ai/timefold/solver/core/impl/exhaustivesearch/scope/ExhaustiveSearchPhaseScope.java
- core/src/main/java/ai/timefold/solver/core/impl/phase/custom/scope/CustomPhaseScope.java
- core/src/main/java/ai/timefold/solver/core/impl/phase/scope/AbstractPhaseScope.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/AbstractCompositeTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/AbstractTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/AndCompositeTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/BasicPlumbingTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/BestScoreFeasibleTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/BestScoreTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/ChildThreadPlumbingTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/OrCompositeTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/PhaseToSolverTerminationBridge.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/ScoreCalculationCountTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/StepCountTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/TimeMillisSpentTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedStepCountTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentScoreDifferenceThresholdTerminationTest.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTerminationTest.java
- docs/src/modules/ROOT/pages/optimization-algorithms/optimization-algorithms.adoc
Closes #731 
The `Unimproved*` classes have the important changes.
The rest is just assorted cleanup while I was already in this ancient part of the codebase.
> fix: unimproved terminations skip construction heuristic

- docs/src/modules/ROOT/pages/constraints-and-score/score-calculation.adoc
- test/src/main/java/ai/timefold/solver/test/api/score/stream/SingleConstraintAssertion.java
- test/src/main/java/ai/timefold/solver/test/impl/score/stream/DefaultSingleConstraintAssertion.java
- test/src/test/java/ai/timefold/solver/test/api/score/stream/SingleConstraintAssertionTest.java
This PR improves the error messages of the constraint verifier and adds two new methods: `justifiesWithExactly()` and `indictsWithExactly()`. The new messages will be formatted as follows:
```
Broken expectation.
Justification: ai.timefold.solver.test.api.score.stream.testdata/Justify with first justification
Expected:
TestFirstJustification[id=2]
Actual:
TestFirstJustification[id=Generated Entity 0]
TestFirstJustification[id=Generated Entity 1]
TestFirstJustification[id=Generated Entity 2]
Expected but not found:
TestFirstJustification[id=2]
Unexpected but found:
TestFirstJustification[id=Generated Entity 0]
TestFirstJustification[id=Generated Entity 1]
TestFirstJustification[id=Generated Entity 2]
```
```
Broken expectation.
Indictment: …
```
> feat: Improve constraint verifier error messages

- benchmark/src/main/java/ai/timefold/solver/benchmark/config/ProblemBenchmarksConfig.java
- benchmark/src/test/java/ai/timefold/solver/benchmark/config/ProblemBenchmarksConfigTest.java
- core/src/main/java/ai/timefold/solver/core/config/util/ConfigUtils.java
This pull request resolves a bug in the benchmark module where metrics are duplicated when running it multiple times, leading to inconsistent results.
The problem is caused by a combination of an existing benchmark config that is created after the first run and the property `inheritedSolverBenchmark`. Therefore,  the method `ai.timefold.solver.benchmark.impl.DefaultPlannerBenchmarkFactory#buildEffectiveSolverBenchmarkConfigList` will duplicate the values when inheriting the configuration at the line `#163`.
The proposed solution fixes the problem by avoiding the duplicates in the config class `ProblemBenchmarksConfig`.
> fix: Benchmark duplicated metrics

- .github/workflows/pull_request.yml
It's too slow, and OpenRewrite is too flaky.
> ci: don't run on MacOS

- core/src/main/java/ai/timefold/solver/core/api/domain/variable/PlanningListVariable.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/variable/descriptor/ListVariableDescriptor.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirector.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirectorFactory.java
- core/src/test/java/ai/timefold/solver/core/impl/constructionheuristic/DefaultConstructionHeuristicPhaseTest.java
- core/src/test/java/ai/timefold/solver/core/impl/exhaustivesearch/DefaultExhaustiveSearchPhaseTest.java
- core/src/test/java/ai/timefold/solver/core/impl/localsearch/DefaultLocalSearchPhaseTest.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/DefaultSolverTest.java
- core/src/test/java/ai/timefold/solver/core/impl/testdata/domain/pinned/allows_unassigned/TestdataAllowsUnassignedPinningFilter.java
- core/src/test/java/ai/timefold/solver/core/impl/testdata/domain/pinned/allows_unassigned/TestdataPinnedAllowsUnassignedEntity.java
- core/src/test/java/ai/timefold/solver/core/impl/testdata/domain/pinned/allows_unassigned/TestdataPinnedAllowsUnassignedSolution.java
- core/src/test/java/ai/timefold/solver/core/impl/testdata/util/PlannerTestUtils.java
- docs/src/modules/ROOT/pages/upgrade-and-migration/upgrade-to-latest-version.adoc
Interestingly, plenty of tests were actually intentionally testing the situation where allowsUnassigned=false and yet value pinned to null, making sure the solver didn't fail in that case.
That was probably an oversight; if I had thought about it more at the time, I would've convinced myself that failing in this situation is the correct behavior. But it raises questions of backwards compatibility.
In my opinion, changing this is not a problem, because before this fix it would result in negative init score, and that would've made local search fail anyway.
> fix: forbid pinning uninitialized entities when unassigned not allowed

- core/src/test/java/ai/timefold/solver/core/impl/util/MathUtilsTest.java
Prevents a failure on M3 Macs.
Also see https://stackoverflow.com/questions/78521763/different-results-of-division-on-m3-mac
> test: add tolerance to double comparison

- docs/src/modules/ROOT/pages/constraints-and-score/score-calculation.adoc
Fixed the `ConstraintCollectors.average()` example referring to `ConstraintCollectors.sum()` instead.
> docs: fix ConstraintCollectors.average() example

- core/src/main/java/ai/timefold/solver/core/config/solver/SolverConfig.java
- core/src/test/java/ai/timefold/solver/core/config/solver/SolverConfigTest.java
- core/src/test/resources/ai/timefold/solver/core/config/solver/testSolverConfigWithoutNamespace.xml
This pull request updates `ai.timefold.solver.core.config.solver.SolverConfig#visitReferencedClasses` to ensure that `nearbyDistanceMeterClass` is visitable, making it available in GIZMO and used by the Quarkus integration.
It was found that the Quarkus Native compilation does not include the Nearby class, resulting in errors like the following:
```
Caused by: java.lang.IllegalArgumentException: Impossible state: could not find the NearbySelectionConfig's nearbyDistanceMeterClass (org.acme.vehiclerouting.domain.LocationDistanceMeter) generated Gizmo supplier.
at ai.timefold.solver.core.config.util.ConfigUtils.newInstance(ConfigUtils.java:23)
at ai.timefold.solver.core.config.util.ConfigUtils.newInstance(ConfigUtils.java:62)
at ai.timefold.solver.core.impl.solver.ClassInstanceCache.lambda$n …
```
> feat: make `nearbyDistanceMeterClass` available for GIZMO

- docs/src/modules/ROOT/pages/upgrade-and-migration/upgrade-to-latest-version.adoc
This pull request standardizes the use of the `minStart` and `maxEnd` variables in the documentation.
Relates to TimefoldAI/timefold-quickstarts#495
> chore: standarize the `minStart` and `maxEnd` variables

- benchmark/src/main/java/ai/timefold/solver/benchmark/impl/DefaultPlannerBenchmark.java
- quarkus-integration/quarkus-benchmark/integration-test/src/main/java/ai/timefold/solver/quarkus/benchmark/it/TimefoldBenchmarkTestResource.java
- quarkus-integration/quarkus-benchmark/integration-test/src/main/java/ai/timefold/solver/quarkus/benchmark/it/domain/StringLengthVariableListener.java
- quarkus-integration/quarkus-benchmark/integration-test/src/main/java/ai/timefold/solver/quarkus/benchmark/it/domain/TestdataListValueShadowEntity.java
- quarkus-integration/quarkus-benchmark/integration-test/src/main/java/ai/timefold/solver/quarkus/benchmark/it/domain/TestdataStringLengthShadowEntity.java
- quarkus-integration/quarkus-benchmark/integration-test/src/main/java/ai/timefold/solver/quarkus/benchmark/it/domain/TestdataStringLengthShadowSolution.java
- quarkus-integration/quarkus-benchmark/integration-test/src/main/java/ai/timefold/solver/quarkus/benchmark/it/solver/TestdataStringLengthConstraintProvider.java
- quarkus-integration/quarkus-benchmark/integration-test/src/main/resources/application.properties
- quarkus-integration/quarkus-benchmark/integration-test/src/test/java/ai/timefold/solver/quarkus/benchmark/it/TimefoldBenchmarkBlueprintTest.java
- quarkus-integration/quarkus-benchmark/integration-test/src/test/java/ai/timefold/solver/quarkus/benchmark/it/TimefoldBenchmarkResourceIT.java
- quarkus-integration/quarkus-benchmark/integration-test/src/test/java/ai/timefold/solver/quarkus/benchmark/it/TimefoldBenchmarkResourceTest.java
- quarkus-integration/quarkus-benchmark/integration-test/src/test/resources/blueprintSolverBenchmarkConfig.xml
This pull request addresses a benchmark failure that occurs due to a bad configuration used during the warm-up phase.
> fix: Continue the benchmark warm-up when one configuration fails

- core/src/main/java/ai/timefold/solver/core/api/score/analysis/ConstraintAnalysis.java
- core/src/main/java/ai/timefold/solver/core/api/score/analysis/ScoreAnalysis.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/InnerScoreDirector.java
- core/src/test/java/ai/timefold/solver/core/api/score/analysis/ScoreAnalysisTest.java
- core/src/test/java/ai/timefold/solver/core/api/solver/SolutionManagerTest.java
- docs/src/modules/ROOT/pages/constraints-and-score/understanding-the-score.adoc
This pull request adds a summary logic to the `ScoreAnalysis` class and addresses minor issues.
> feat: Improve `ScoreAnalysis` debug information

- core/src/main/java/ai/timefold/solver/core/impl/localsearch/DefaultLocalSearchPhaseFactory.java
- core/src/test/java/ai/timefold/solver/core/impl/localsearch/DefaultLocalSearchPhaseTest.java
- core/src/test/java/ai/timefold/solver/core/impl/testdata/domain/chained/TestdataChainedSolution.java
This pull request updates the list of default moves for multi-variable domain models.
> fix: Change the default moves for multi-variable domain models

- docs/src/modules/ROOT/nav.adoc
Communication about new versions of the Timefold Solver happens via https://github.com/TimefoldAI/timefold-solver/releases
This commit links to that page from within the Antora docs navigation. So it becomes easier to find for people exploring the docs.
> chore: link the Github Release page from within docs

- .github/workflows/downstream_benchmarks.yml
- .github/workflows/downstream_enterprise.yml
- .github/workflows/downstream_python_enterprise.yml
- .github/workflows/downstream_python_quickstarts.yml
- .github/workflows/downstream_quickstarts.yml
- .github/workflows/safe_for_ci.yml
- .github/workflows/sonarcloud.yml
This PR makes it so that pull requests that could steal secrets now require a specific label.
It also makes it so that a workflow runs automatically to grant that label to PRs by trusted users.
> ci: external contributions require a label before CI can run

- .github/workflows/downstream_benchmarks.yml
- .github/workflows/downstream_enterprise.yml
- .github/workflows/downstream_python_enterprise.yml
- .github/workflows/sonarcloud.yml
Do not require a team when checking if the PR author is a member of the organisation in GH workflows.
> chore: do not require team during auth

- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/composite/UnionMoveSelectorFactory.java
This PR fixes a bug when there are nested `UnionMoveSelectorConfig` configurations and does not duplicate configurations, which causes the following:
```
java.lang.IllegalArgumentException: The selector configuration (ListChangeMoveSelectorConfig(ValueSelectorConfig(null), DestinationSelectorConfig(null, null))) already includes the Nearby Selection setting, making it incompatible with the top-level property nearbyDistanceMeterClass (class ai.timefold.solver.benchmarks.examples.vehiclerouting.domain.solver.nearby.CustomerNearbyDistanceMeter).
Remove the Nearby setting from the selector configuration or remove the top-level nearbyDistanceMeterClass.
```
> fix: Avoid duplicating nearby configuration

- core/src/main/java/ai/timefold/solver/core/api/solver/ProblemSizeStatistics.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/solution/descriptor/SolutionDescriptor.java
- core/src/test/java/ai/timefold/solver/core/api/solver/ProblemSizeStatisticsTest.java
- core/src/test/java/ai/timefold/solver/core/impl/domain/solution/descriptor/SolutionDescriptorTest.java
This pull request addresses the issue with the statistics when the range value list is empty.
> fix: address scale equal to NaN

- python/jpyinterpreter/src/main/python/__init__.py
- python/jpyinterpreter/src/main/python/jvm_setup.py
- python/jpyinterpreter/tests/test_jvm_setup.py
- python/python-core/src/main/python/_timefold_java_interop.py
This PR improves the compatibility JVM error messages.
> feat: improve JVM exceptions

- core/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirector.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/AbstractScoreDirectorFactory.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/InnerScoreDirector.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/InnerScoreDirectorFactory.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/stream/BavetConstraintStreamScoreDirector.java
- core/src/main/java/ai/timefold/solver/core/impl/score/director/stream/BavetConstraintStreamScoreDirectorFactory.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/BavetConstraintFactory.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/BavetConstraintSession.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/BavetConstraintSessionFactory.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/NodeNetwork.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/common/AbstractConstraintStreamScoreDirectorFactory.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolutionManager.java
- core/src/test/java/ai/timefold/solver/core/api/solver/SolverFactoryTest.java
- test/src/main/java/ai/timefold/solver/test/impl/score/stream/DefaultMultiConstraintVerification.java
- test/src/main/java/ai/timefold/solver/test/impl/score/stream/DefaultSingleConstraintVerification.java
Contains two commits:
- First fixes the actual issue.
- Second refactors some of the code to decrease complexity, as recommended by Sonar. The logic of the code did not change, only who calls what from where.
Merge individually, do not squash.
> fix: prevent excessive logging of constraint weights

- docs/src/modules/ROOT/pages/introduction/introduction.adoc
This PR adds content new planning and planning AI content to the introduction.
I've reused some of the existing heading anchors to prevent links failing.
@triceo if this isn't quite what you had in mind, let me know and we can revisit.
> docs: add new intro to planning and planning ai intro

- core/src/main/java/ai/timefold/solver/core/api/solver/SolverJobBuilder.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/ConsumerSupport.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolverJob.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolverJobBuilder.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolverManager.java
- core/src/test/java/ai/timefold/solver/core/api/solver/SolverManagerTest.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/ConsumerSupportTest.java
- python/python-core/src/main/python/_solver_manager.py
- python/python-core/tests/test_solver_manager.py
This pull request adds a new job configuration that allows an action to be run when the solver starts the solving process. The current approach uses a `PhaseLifecycleListenerAdapter` to trigger the event because the API `SolverEventListener` would need to be changed in order to add a new solver event.
> feat: add solver job start event

- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/common/AbstractIndexedJoinNode.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/common/AbstractJoinNode.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/common/AbstractUnindexedJoinNode.java
Tuple updates are done very frequently.
As I was benchmarking a different issue, I noticed that we create gigabytes of large capturing lambdas during tuple update, and therefore on the hot path.
This refactoring intends to decrease the number of lambdas created, as well as make them capture less and contain less conditional logic, helping with branch predictions.
> perf: decrease lambda creation on the hot path during tuple update

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_quickstarts.yml
- .github/workflows/pull_request_secure.yml
- .github/workflows/release.yml
- migration/pom.xml
Blocked by https://github.com/openrewrite/rewrite/issues/4534
> ci: upgrade workflows to Java 23

- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/school-timetabling/school-timetabling-constraints.adoc
- docs/src/modules/ROOT/pages/using-timefold-solver/modeling-planning-problems.adoc
fixes #1202
Another pull request will have to be created to re-align the getting started docs
> docs: correct documentation

- docs/src/modules/ROOT/pages/.index.adoc
- docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/quarkus-vehicle-routing/quarkus-vehicle-routing-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/constrainttests.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/java-logback-config.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/java-prerequisites.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/school-timetabling/school-timetabling-constraints.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/school-timetabling/school-timetabling-model.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/school-timetabling/school-timetabling-solution.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/solutionsourcecode.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/try-the-application.adoc
- docs/src/modules/ROOT/pages/quickstart/shared/whatyoubuild.adoc
- docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
fixes #1205
Because of the duplication between programming languages and frameworks, also experimented with splitting up the files a bit and including shared files. 
For the existing shared files, i noticed the Python tab was also showing when running the Spring / Quarkus quickstarts, so i used a property to disable (aka hide) the python tabs in these cases.
> docs: align getting started

- docs/src/modules/ROOT/pages/quickstart/shared/constrainttests.adoc
Apparently the Docs are not part of the regular build. There was a mistake in the import.
> docs: correct badly imported sourcecode.

- migration/src/main/java/ai/timefold/solver/migration/v8/NullableRecipe.java
Hi! Great to see the recipes here; I do have one request: can we make the order of the recipe list stable?
For context: we generate documentation for recipes, even when maintained externally. Before this change we would see a new recipe list order for every run. After this change the order should be fixed, such that we do not keep changing that documentation page every time.
Thanks in advance!
> fix: Use a stable recipe order for `NullableRecipe.getRecipeList()`

- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/list/ElementLocationRandomIterator.java
- core/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/list/ElementDestinationSelectorTest.java
The error caused the skipping of one entity's list variable as a possible location. 
In the case of only one entity being available, this would lead to not assigning any value to any list variable - which is how the bug was discovered.
> fix: off-by-one error when choosing element locations

- python/python-core/src/main/python/domain/_annotations.py
> fix: More accurate type hints for Python @planning_entity

- docs/src/modules/ROOT/pages/using-timefold-solver/modeling-planning-problems.adoc
- python/python-core/src/main/python/domain/_annotations.py
- python/python-core/tests/test_domain.py
This brings parity with the Java version (I also found that DeepPlanningClone did not work on a planning solution ProblemFactCollectionProperty, whereas marking the entire class to deep clone does)
> feat: Support deep_planning_clone class decorator

- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/RuinRecreateMove.java
- core/src/test/java/ai/timefold/solver/core/impl/move/director/MoveDirectorTest.java
Fixes https://github.com/TimefoldAI/timefold-employee-scheduling/issues/318
> fix: use a different `SolverScope` in the `RuinRecreateMove` nested phase

- core/src/main/java/ai/timefold/solver/core/api/solver/Solver.java
- core/src/main/java/ai/timefold/solver/core/api/solver/SolverManager.java
- core/src/main/java/ai/timefold/solver/core/api/solver/change/ProblemChange.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/AbstractSolver.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/BestSolutionHolder.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/DefaultSolver.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/BasicPlumbingTermination.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/termination/BasicPlumbingTerminationTest.java
We have seen reports of the TreeMap getting concurrently accessed and throwing exceptions. Unfortunately, we have never seen any code to reproduce these failures, as concurrency issues are notoriously hard to reproduce. Therefore we refactor the mechanism to make any such issues impossible.
For the same reason as there is no reproducer, there is also no new test coverage. But existing test coverage still passes.
> fix: prevent possible concurrent modification of a collection

- docs/src/modules/ROOT/pages/quickstart/hello-world/hello-world-quickstart.adoc
In section **8. Create the application**, there is a line: 
```python
return Timetable(demo_data.name, timeslots, rooms, lessons)
```
This will cause `NameError: name 'demo_data' is not defined` because `demo_data` is not defined anywhere in the `generate_demo_data()` function.  A possible hotfix is to just directly assign a name:
```python
return Timetable("DEMO_DATA", timeslots, rooms, lessons)
```
>  docs: hotfix a minor error in the python quickstarts tutorial. 

- .github/workflows/pull_request_secure.yml
This PR removes the adoc files from the ignored paths because we have a deployment job that should trigger whenever an adoc file is updated.
We will still run some unnecessary jobs, but it is necessary to continue using the secured workflow.
> chore: enable CI when updating only .adoc files

- docs/src/modules/ROOT/pages/quickstart/shared/try-the-application.adoc
The sample quarkus application only uses a `/timetables` endpoint, not a `/timetables/solve` endpoint.
> docs: Use correct quarkus endpoint in quickstart guide

- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
To address this during compilation:
```
[ERROR] 'dependencies.dependency.version' for ai.timefold.solver:timefold-solver-test:jar is missing.
```
> docs: specified timefold-solver-test dependency version

- docs/src/modules/ROOT/pages/quickstart/shared/constrainttests.adoc
The variable is setup as `ROOM`, but used as `ROOM1`.
> docs: ROOM variable naming consistency

- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
The docs are missing a dependency record for rest-assured.
This clears that up.
> docs: add rest-assured dependency

- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
I might be running a different version of Java, but i had to explicitly import a couple of `java.io` objects.
> docs: importing java.io objects for TimetableResourceTest

- docs/src/modules/ROOT/pages/quickstart/quarkus-vehicle-routing/quarkus-vehicle-routing-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/quarkus/quarkus-quickstart.adoc
- docs/src/modules/ROOT/pages/quickstart/spring-boot/spring-boot-quickstart.adoc
Sending a problem to the APIs should now all be `POST /<problem>` not `POST /<problem>/solve`
Also fixed a variable substitution issue.
> docs: align api structure for quickstarts

- docs/src/modules/ROOT/pages/quickstart/shared/school-timetabling/school-timetabling-model.adoc
My tests were failing because of this error:
```
/src/test/java/org/acme/schooltimetabling/solver/TimetableConstraintProviderTest.java:[28,30] no suitable constructor found for Lesson(java.lang.String,java.lang.String,java.lang.String,java.lang.String,org.acme.schooltimetabling.domain.Timeslot,org.acme.schooltimetabling.domain.Room)
```
So i borrowed a second constructor from some of the OptaPlanner docs.
> docs: Lesson constructor for tests

- docs/src/modules/ROOT/pages/integration/integration.adoc
- docs/src/modules/ROOT/pages/upgrading-timefold-solver/framework-version-warning.adoc
- docs/src/modules/ROOT/pages/upgrading-timefold-solver/upgrade-from-optaplanner.adoc
- docs/src/modules/ROOT/pages/upgrading-timefold-solver/upgrade-to-latest-version.adoc
After interaction on Stack Overflow, noticed that we do not document our minimal Spring Boot Version. 
Fixing that in this PR: https://stackoverflow.com/questions/79488759/move-from-optaplanner-to-timefold-results-in-spring-error
> docs: clarify migration limitations

- .github/workflows/codeql.yml
The analysis was complaining about missing configs.
With this PR, it no longer does.
> ci: add CodeQL JavaScript config

- docs/src/modules/ROOT/pages/constraints-and-score/understanding-the-score.adoc
- docs/src/modules/ROOT/pages/optimization-algorithms/local-search.adoc
- docs/src/modules/ROOT/pages/upgrading-timefold-solver/backwards-compatibility.adoc
- docs/src/modules/ROOT/pages/using-timefold-solver/modeling-planning-problems.adoc
A community member gave feedback that our documentation doesn't clearly show how to enable preview features.
This PR addresses that.
> docs: improve documentation on configuration of preview feature.

- benchmark/src/main/java/ai/timefold/solver/benchmark/impl/result/ProblemBenchmarkResult.java
- benchmark/src/test/resources/dummyPlannerBenchmarkResult.xml
This is a copy of @Magnusrk's PR: https://github.com/TimefoldAI/timefold-solver/pull/1566
I needed to make automatic formatting changes and due to the fact that Magnus committed his changes directly to `main`, I decided not to try to push to his repo directly.
I kept the attribution of the commit to Magnus.
> fix: support MoveCountPerTypeProblemStatistic in JAXB mapping

- core/src/test/java/ai/timefold/solver/core/testutil/AbstractMeterTest.java
- core/src/test/java/ai/timefold/solver/core/testutil/PlannerTestUtils.java
Flaky test: https://github.com/TimefoldAI/timefold-solver/actions/runs/15161156113/job/42627376418?pr=1593
> fix: attempt to fix flaky tests

- core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/decorator/FilteringMoveSelector.java
- core/src/main/java/ai/timefold/solver/core/impl/localsearch/DefaultLocalSearchPhase.java
- core/src/main/java/ai/timefold/solver/core/impl/phase/AbstractPhase.java
- core/src/main/java/ai/timefold/solver/core/impl/phase/scope/AbstractPhaseScope.java
- core/src/test/java/ai/timefold/solver/core/impl/heuristic/selector/move/decorator/FilteringMoveSelectorTest.java
This PR ensures that the `FilteringMoveSelector` will honor the phase termination setting. There may be use cases where a move filtering filters out all moves, resulting in the iterator analyzing a large number of moves before returning no valid upcoming selection.
It is important to note that the proposed strategy may not work for every termination configuration, and the phase will only end after the move selector bails out. Termination not based on time can cause the process to stuck during the generation of the first valid move in the phase, which may result in no move being returned after bailing out.
> chore: filtering move selector honoring the phase termination

- core/src/main/java/ai/timefold/solver/core/impl/domain/common/ReflectionHelper.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/common/accessor/ReflectionBeanPropertyMemberAccessor.java
- core/src/main/java/ai/timefold/solver/core/impl/domain/entity/descriptor/EntityDescriptor.java
- core/src/main/java/ai/timefold/solver/core/impl/score/stream/bavet/BavetConstraintFactory.java
- core/src/test/java/ai/timefold/solver/core/impl/domain/common/accessor/ReflectionBeanPropertyMemberAccessorTest.java
- core/src/test/java/ai/timefold/solver/core/testdomain/invalid/gettersetter/TestdataDifferentGetterSetterVisibilityEntity.java
- core/src/test/java/ai/timefold/solver/core/testdomain/invalid/gettersetter/TestdataInvalidGetterEntity.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataBendableBigDecimalScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataBendableLongScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataBendableScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataHardMediumSoftBigDecimalScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataHardMediumSoftLongScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataHardMediumSoftScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataHardSoftBigDecimalScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataHardSoftLongScoreSolution.java
- core/src/test/java/ai/timefold/solver/core/testdomain/score/TestdataHardSoftScoreSolution.java
- docs/src/modules/ROOT/pages/upgrading-timefold-solver/upgrade-to-latest-version.adoc
- quarkus-integration/quarkus/deployment/src/test/java/ai/timefold/solver/quarkus/TimefoldProcessorGeneratedGizmoSupplierTest.java
- quarkus-integration/quarkus/deployment/src/test/java/ai/timefold/solver/quarkus/testdomain/gizmo/TestDataKitchenSinkEntity.java
If a getter exists, a setter has to.
If a setter exists, a getter has to.
Both getter and setter need to have the same visibility.
> chore: enforce consistency between variable getters and setters

- test/src/main/java/ai/timefold/solver/test/api/score/stream/ConstraintVerifier.java
I noticed when trying out Declarative Shadow Variables that I had no way to enable preview features in the `ConstraintVerifier`. Specifically, when writing tests I hit [this case](https://github.com/TimefoldAI/timefold-solver/blob/7bce5c216bac44f0d08938b6679083d10bcda408/core/src/main/java/ai/timefold/solver/core/impl/domain/variable/declarative/DeclarativeShadowVariableDescriptor.java#L37) even if I created the `ConstraintVerifier` with a `SolverConfig` that included the declarative shadow variable preview feature.
This PR just passes the enabled preview feature set from the provided `SolverConfig` in `ConstraintVerifier::create` so we can test constraints using preview features. Let me know if there's a better way to achieve this.
I'd be happy to write a test for this if you think …
> fix: Pass SolverConfig's enabled preview feature set to ConstraintVerifier on creation

- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/DiminishedReturnsTermination.java
- core/src/main/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTermination.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/termination/DiminishedReturnsTerminationTest.java
- core/src/test/java/ai/timefold/solver/core/impl/solver/termination/UnimprovedTimeMillisSpentTerminationTest.java
When the phase start takes a long time (such as when nearby distance matrix is computed), that time will eat into the grace period of diminished returns, and possibly entirely eradicate it. Therefore we only start the grace period at first step start.
> fix: start the termination counter at the first step
